[build]
  command = "pnpm install && pnpm build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip = false

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18"
  NPM_VERSION = "10"
  PNPM_VERSION = "8.15.6"

[build.cache]
  paths = [
    "node_modules/**/*",
    ".pnpm-store/**/*"
  ]